pipeline {
  agent any

  environment {
    IMAGE_NAME = "sathiyanarayanan07/backend_app"
    IMAGE_TAG ="${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

     stage('Build Docker Image') {
            steps {
              dir('backend_app'){
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
              }
            }
        }
    stage('Install Dependencies') {
      steps {
        dir('backend_app') {
          sh 'npm install'
        }
      }
    }
    stage('RUN Tests') {
      steps {
        dir('backend_app') {
          sh 'npm test || true'
        }
      }
    }

      stage('login to Dockerhub') {
        steps {
          withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
            )]) {
               sh 'echo $DOCKER_PASS |docker login -u $DOCKER_USER --password-stdin'
          }
        }
      }

    stage('push Image') {
      steps {
        sh ' docker push $IMAGE_NAME:$IMAGE_TAG'
      }
    }

        stage('Deploy') {
            steps {
    
                sh 'docker rm -f backend_app || true'
                sh 'docker run -d -p 3000:3000 --name backend_app $IMAGE_NAME:$IMAGE_TAG'
            }
        }
  }
}




















 
