pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

     stage('Build Docker Image') {
            steps {
                sh 'docker build -t backend_app:latest .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker rm -f backend_container || true'
                sh 'docker run -d -p 3000:3000 --name backend_container backend_app:latest'
            }
        }
  }
}




















 
